spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.shiro.shirospringboot.bean